name: PR Description, Target Checker, Version, and Close the PR having DO NOT MERGE LABEL

on:
  workflow_dispatch:
     inputs:
      EVENT_CHECK_VARIABLE:
        description: 'Description of the event check variable.'
        required: true
        type: string
      GITHUB_TOKEN:
        description: 'GitHub token for authentication.'
        required: true
        type: string
      REPO_NAME:
        description: 'Repository name.'
        required: true
        type: string
      PR_NUMBER:
        description: 'Pull request number.'
        required: true
        type: string
      EVENT:
        description: 'Description of the event.'
        required: true
        type: string
      WEBHOOK:
        description: 'Webhook URL.'
        required: true
        type: string

permissions: write-all

env:
  EVENT_CHECK_VARIABLE: 'pull'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REPO_NAME: ${{ github.repository }}
  PR_NUMBER: ${{ github.event.pull_request.number }}
  EVENT: ${{ github.event.action }}
  WEBHOOK: ${{ secrets.GCHAT_WEBHOOK_URL }}

jobs:
  Check-PR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: PR Description ,Target Checker ,Version and Close the PR having DO NOT MERGE LABEL
        id: latestTag
        run: |
          if [ -f "VERSION" ]; then
            echo " File is present"        
            version_file=$(cat VERSION)
            echo "version from version_file -> $version_file"
            echo "version_file=$version_file" >> $GITHUB_OUTPUT
          else 
           echo "no file"
          fi
      - name: PR Description ,Target Checker ,Version and Close the PR having DO NOT MERGE LABEL
        uses: ./
        env:
          VERSION_FILE: ${{ steps.latestTag.outputs.version_file }}
        

        
            
      
      