name: PR Description, Target Checker, Version, and Close the PR having DO NOT MERGE LABEL

# Add the on.workflow_call trigger to make the workflow reusable
on:
  workflow_call:
    inputs:
      action:
        required: true
        type: string

permissions: write-all

env:
  EVENT_CHECK_VARIABLE: 'pull'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REPO_NAME: ${{ github.repository }}
  PR_NUMBER: ${{ github.event.pull_request.number }}
  EVENT: ${{ github.event.action }}
  WEBHOOK: ${{ secrets.GCHAT_WEBHOOK_URL }}

jobs:
  Check-PR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: PR Description, Target Checker, Version, and Close the PR having DO NOT MERGE LABEL
        id: latestTag
        run: |
          if [ -f "VERSION" ]; then
            echo "File is present"
            version_file=$(cat VERSION)
            echo "version from version_file -> $version_file"
            echo "version_file=$version_file" >> $GITHUB_OUTPUT
          else
            echo "no file"
          fi

      # Accept input parameters if needed
      - name: Set input parameters
        if: ${{ github.event_name == 'workflow_call' }}
        run: |
          echo "Input parameters received:"
          echo "Action: ${{ github.event.inputs.action }}"