#  Description: This workflow is scheduled to check for stale pull requests and close them after two days of inactivity.
name: Stale Pull Requests
on:
  workflow_dispatch:
    inputs:
      EVENT_CHECK_VARIABLE:
        description: 'Description of the event check variable.'
        required: true
        type: string
      PAT:
        description: 'GitHub token for authentication.'
        required: true
        type: string
      REPO_NAME:
        description: 'Repository name.'
        required: true
        type: string
      WEBHOOK:
        description: 'Webhook URL.'
        required: true
        type: string
      

permissions: write-all
jobs:
  Stale-PR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Display Input Variables
        run: |
          echo "EVENT_CHECK_VARIABLE: ${{ github.event.inputs.EVENT_CHECK_VARIABLE }}"
          echo "PAT: ${{ github.event.inputs.PAT }}"
          echo "REPO_NAME: ${{ github.event.inputs.REPO_NAME }}"
          echo "WEBHOOK: ${{ github.event.inputs.WEBHOOK }}"
          
      - name: Execute Stale  Action
        uses: ./  # Assuming your action file is located in the root directory
        with:
          PAT: ${{ github.event.inputs.PAT }}
          REPO_NAME: ${{ github.event.inputs.REPO_NAME }}
          WEBHOOK: ${{ github.event.inputs.WEBHOOK }}
          EVENT_CHECK_VARIABLE: ${{ github.event.inputs.EVENT_CHECK_VARIABLE }}