#  Description: This workflow is tigger on close event   to check for stale pull requests and close them after two days of inactivity.
on:
  workflow_dispatch:
    inputs:
      GITHUB_TOKEN:
        description: 'GitHub token for authentication.'
        required: true
        type: string
      UserName:
        description: 'User name.'
        required: true
        type: string
      Owner:
        description: 'Owner'
        required: true
        type: string
      VERSION_FILE:
        description: 'VERSION_FILE.'
        required: true
        type: string
        
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git and create tag
        run: |
          git config --global user.email "actions@example.com"
          git config --global user.name "GitHub Actions"
          echo "VERSION_FILE: ${{ github.event.inputs.VERSION_FILE }}"
          git tag -a ${{ github.event.inputs.VERSION_FILE }} -m "Version ${{ github.event.inputs.VERSION_FILE }}"
          git push https://${{ github.event.inputs.UserName }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.event.inputs.Owner }}/repo.git --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 