#  Description: This workflow is tigger on close event   to check for stale pull requests and close them after two days of inactivity.
on:
  workflow_dispatch:
    inputs:
      GITHUB_TOKEN:
        description: 'GitHub token for authentication.'
        required: true
        type: string
      VERSION_FILE:
        description: 'VERSION_FILE.'
        required: true
        type: string
      REPO_NAME:
        description: 'REPO_NAME.'
        required: true
        type: string
      REPO_OWNER:
        description: 'Owner of the source repository.'
        required: true
        type: string
        
        
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.REPO_OWNER }}/${{ github.event.inputs.REPO_NAME }}
          ref: master # or specify the branch you want to use
          token: ${{ github.event.inputs.GITHUB_TOKEN }}
        
      - name: Read version from file
        id: version
        run: echo "VERSION=$(cat ${{ github.event.inputs.VERSION_FILE }})" >> $GITHUB_ENV
      - name: Create tag
        run: |
          git config --global user.email "rajvmalasoni@gmail.com"
          git config --global user.name "GitHub Actions"
          git tag -a $VERSION -m "Version $VERSION"
          echo "Created tag: $VERSION"
        
      - name: Push tag
        run: git push origin $VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}